name: Build & Publish Docker (GHCR)

on:
  workflow_dispatch:
    inputs:
      extra_tag:
        description: 'Optional additional tag (e.g. v1.2.3)'
        required: false
        default: ''
      push:
        description: 'Push image to GHCR (true/false)'
        required: true
        default: 'true'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/maya-brew
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.event.inputs.extra_tag }},enable=${{ github.event.inputs.extra_tag != '' }}
            type=sha

      - name: Build & (optionally) push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event.inputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        if: ${{ github.event.inputs.push == 'true' }}
        run: |
          echo "Published tags:"
          echo "${{ steps.meta.outputs.tags }}" | tr ' ' '\n'
