---
# This GitHub Actions workflow is triggered by pull requests, pushes to the
# develop branch, and manual dispatch events. It sets up a Python environment,
# installs project dependencies, and then runs Super-Linter on the codebase.
# The workflow is configured to validate the entire codebase with custom
# linting rules and saves the linter output and summary as artifacts.

name: Lint Code Base

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: write   # allow pushing auto-fix commits
  packages: read
  statuses: write

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure git for auto-fix commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Install Dependencies
        run: |
          pip install -e .[dev] --target .venv

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@ffde3b2b33b745cb612d787f669ef9442b1339a6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          APPLY_FIXES: true           # enable auto-fixes
          APPLY_FIXES_EVENT: push     # only attempt fixes on push (not PR)
          APPLY_FIXES_MODE: commit    # commit directly to the branch
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_ISORT: false
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: ./pyproject.toml
          PYTHONPATH: "${{ github.workspace }}/.venv"
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_JSCPD: false


