---
# This GitHub Actions workflow is triggered by pull requests, pushes to the
# develop branch, and manual dispatch events. It sets up a Python environment,
# installs project dependencies, and then runs Super-Linter on the codebase.
# The workflow can auto-fix issues on push (committing directly) and produce
# a PR commit with fixes (via git-auto-commit-action) when running in PRs.

name: Lint Code Base

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: write
  statuses: write

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies
        run: |
          pip install -e .[dev] --target .venv
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@ffde3b2b33b745cb612d787f669ef9442b1339a6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          APPLY_FIXES: true
          APPLY_FIXES_EVENT: push
          APPLY_FIXES_MODE: commit
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: ./pyproject.toml
          PYTHONPATH: "${{ github.workspace }}/.venv"
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_JSCPD: false
          FIX_ENV: true
          FIX_GITHUB_ACTIONS_ZIZMOR: true
          FIX_JSON_PRETTIER: true
          FIX_JSON: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_NATURAL_LANGUAGE: true
          FIX_POWERSHELL: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_RUFF: true
          FIX_YAML_PRETTIER: true
      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
