name: Publish to TestPyPI

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@56b0cd341142dac1891eb3e08ba47a22799bbd05
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dynamic versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]>=1.4.0"

      - name: Install dependencies (no root)
        run: poetry install --no-interaction --no-root --sync

      - name: Show resolved dynamic version
        run: poetry dynamic-versioning show || echo "(Command not available; plugin should still run during build)"

      - name: Build distribution (dynamic version applied)
        run: poetry build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@ab69e431e9c9f48a3310be0a56527c679f56e04d
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          skip-existing: true
