name: Pytest Maya 2026

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: read

jobs:
  mayapy-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/maya-brew:sha-9daa1a4
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Set up Python (for Poetry export)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@56b0cd341142dac1891eb3e08ba47a22799bbd05
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Cache dependencies (pip/venv/wheelhouse)
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
            wheelhouse
          key: mayapy-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Export pinned requirements (including dev)
        run: |
          poetry export -f requirements.txt --with dev --without-hashes -o requirements-dev.txt
          echo "Exported requirements:" && head -n 20 requirements-dev.txt || true
      - name: Download dependency wheels (host Python)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          mkdir -p wheelhouse
          pip download -r requirements-dev.txt -d wheelhouse
          echo "Wheelhouse contents (truncated):" && find wheelhouse -mindepth 1 -maxdepth 1 -type f | sed 's#.*/##' | head -n 40 || true
      - name: Install deps into mayapy from wheelhouse (offline)
        run: |
          mayapy -m pip install --upgrade pip
          mayapy -m pip install --no-index --find-links wheelhouse -r requirements-dev.txt
      - name: Install project (source)
        run: |
          mayapy -m pip install .
      - name: Run pytest
        shell: bash
        run: mayapy -m pytest tests/ -q
      - name: Summary
        if: success()
        run: echo "mayapy pytest run succeeded (offline wheelhouse install)." >> "$GITHUB_STEP_SUMMARY"
