name: Pytest Maya 2026

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: read

jobs:
  mayapy-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/maya-brew:sha-9daa1a4
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 1
      - name: Install Poetry into mayapy
        run: |
          set -eux
          # pip already available in mayapy; just upgrade tooling and install Poetry
          mayapy -m pip install --upgrade pip setuptools wheel
          mayapy -m pip install "poetry==1.8.3"
          mayapy -m poetry --version
      - name: Cache wheelhouse
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            wheelhouse
          key: mayapy-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Export pinned requirements (including dev)
        run: |
          set -eux
          mayapy -m poetry export -f requirements.txt --with dev --without-hashes -o requirements-dev.txt
          echo "Exported requirements (first lines):" && head -n 20 requirements-dev.txt || true
      - name: Download dependency wheels (mayapy Python)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          set -eux
          mkdir -p wheelhouse
          mayapy -m pip download -r requirements-dev.txt -d wheelhouse
          echo "Wheelhouse contents (truncated):" && find wheelhouse -mindepth 1 -maxdepth 1 -type f | sed 's#.*/##' | head -n 40 || true
      - name: Install deps into mayapy from wheelhouse (offline)
        run: |
          set -eux
          mayapy -m pip install --no-index --find-links wheelhouse -r requirements-dev.txt
      - name: Install project (source)
        run: |
          set -eux
          mayapy -m pip install .
      - name: Run pytest
        shell: bash
        run: mayapy -m pytest tests/ -q
      - name: Summary
        if: success()
        run: echo "mayapy pytest run succeeded (offline wheelhouse install)." >> "$GITHUB_STEP_SUMMARY"
