name: Pytest Maya 2026

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: read

jobs:
  mayapy-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/maya-brew:sha-9daa1a4
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Install requirements
        run: mayapy -m pip install .[dev]

      - name: Run pytest
        shell: bash
        run: mayapy -m pytest tests/

      - name: Summary
        if: success()
        run: echo "mayapy pytest run succeeded." >> "$GITHUB_STEP_SUMMARY"

